### ISSUE TITLE
 Is there a plugin to support gradle?

### ISSUE THREAD

**Issue by dunmengjun** [electronicarts/ea-async#19]
:)

**Comment by JoeHegarty** [comment]
There is currently no Gradle plugin. 
The easiest way would likely be to to use the command line tool as the final step in your Gradle build. 
I’d like to support Gradle but I haven’t had time to look into that yet.

**Comment by juddgaddie** [comment]
+1

**Comment by elventear** [comment]
Using this snippet in my build script seems to be working for me:
```groovy
dependencies {
    ...
    compileOnly "com.ea.async:ea-async:1.2.1"
}

task instrument(type: JavaExec) {
    main = 'com.ea.async.instrumentation.Main'
    classpath = sourceSets.main.compileClasspath
    args "$buildDir"
}

compileJava.doLast {
    tasks.instrument.execute()
}
```

**Comment by JoeHegarty** [comment]
Resolved in #46 thanks to @Fleex255

**Comment by sevenaper** [comment]
> Using this snippet in my build script seems to be working for me:
> 
> ```groovy
> dependencies {
>     ...
>     compileOnly "com.ea.async:ea-async:1.2.1"
> }
> 
> task instrument(type: JavaExec) {
>     main = 'com.ea.async.instrumentation.Main'
>     classpath = sourceSets.main.compileClasspath
>     args "$buildDir"
> }
> 
> compileJava.doLast {
>     tasks.instrument.execute()
> }
> ```

Thank you very much. But task.execute() can not be used after gradle 5.0. And I change it to compileJava.dependsOn(tasks.instrument), but it does not work. Do you know how to fix it?

**Comment by Fleex255** [comment]
I haven't tested that kind of setup, but I think the `instrument` task needs to depend on `compileJava` so that instrumentation occurs after compilation. Then the Java plugin's `classes` task must be made to depend on `instrument` as well so that the build process always includes the instrumentation.

**Comment by sevenaper** [comment]
> I haven't tested that kind of setup, but I think the `instrument` task needs to depend on `compileJava` so that instrumentation occurs after compilation. Then the Java plugin's `classes` task must be made to depend on `instrument` as well so that the build process always includes the instrumentation.

I have tried both. But neither of them can work.

**Comment by ctemple** [comment]
> > 在我的构建脚本中使用此代码段似乎对我有用：
> > ```groovy
> > dependencies {
> >     ...
> >     compileOnly "com.ea.async:ea-async:1.2.1"
> > }
> > 
> > task instrument(type: JavaExec) {
> >     main = 'com.ea.async.instrumentation.Main'
> >     classpath = sourceSets.main.compileClasspath
> >     args "$buildDir"
> > }
> > 
> > compileJava.doLast {
> >     tasks.instrument.execute()
> > }
> > ```
> 
> 谢谢。但是 task.execute（） 在 gradle 5.0 之后不能使用。我把它改成 compileJava.dependsOn（tasks.instrument），但它不起作用。你知道如何解决它吗？

dependencies {
    ...
    compileOnly "com.ea.async:ea-async:1.2.1"
}

task instrument(type: JavaExec) {
    main = 'com.ea.async.instrumentation.Main'
    classpath = sourceSets.main.compileClasspath
    args "$buildDir"
}

compileJava.finalizedBy(instrument)
