### ISSUE TITLE
is possible to support slf4j mdc

### ISSUE THREAD

**Issue by the-world-wang** [electronicarts/ea-async#26]
![2018-08-07 11 31 26](https://user-images.githubusercontent.com/15126992/43752921-db9d3858-9a35-11e8-893f-d367b0067761.png)
code like this logged during callback ? 
or some good suggestion？

**Comment by JoeHegarty** [comment]
I am not really sure what the question is here. What kind of support do you need?

**Comment by the-world-wang** [comment]
I mean can I get some variable from context(maybe ThreadLocal) in callback？

**Comment by JoeHegarty** [comment]
ea-async doesn't have any impact on threading, it's just like using `.thenRun` or `.thenAccept` etc on the CompletableFuture so the threads will never change unless you explicitly request it. As such this should just work.
