### ISSUE TITLE
How to cancel a Promise ?

### ISSUE THREAD

**Issue by pirix-gh** [electronicarts/ea-async#28]
How do you cancel a Promise that was submitted to await() ?
Will I be able to call .cancel() while it's being processed ?

**Comment by Maia-Everett** [comment]
I'm not an ea-async developer, but I see no reason why you shouldn't be able to cancel a `CompletableFuture` being awaited. It should complete with a `CancellationException` and thus cause the await to throw, same as if any other exception occurred during the `CompletableFuture`'s resolution.

**Comment by JoeHegarty** [comment]
That'a correct @Maia-Everett. ea-async isn't an async library itself, so things like Cancellation are provided by the underlying library, CompletableFutures in this case.
