### ISSUE TITLE
Support arbitrary implementations of CompletionStage<T>

### ISSUE THREAD

**Issue by HaloFour** [electronicarts/ea-async#3]
Currently there is support for instrumenting methods that return/await classes that derive from `CompletableFuture<T>`.  How about also supporting classes or interfaces that implement or extend `CompletionStage<T>`, with which the class would be treated as a `CompletionStage<T>` during instrumentation?

I've seen a couple of libraries where methods returns interfaces that extend `CompletionStage<T>`.  For example, the [Lettuce](https://github.com/mp911de/lettuce) Redis client offers an asynchronous API that returns a `RedisFuture<T>` interface which extends `CompletionStage<T>` and `Future<T>` interfaces as well as providing a few additional methods.  The internal implementation of that interface is derived from `CompletableFuture<T>`.  Because of this the library isn't supported by ea-async.

**Comment by DanielSperry** [comment]
@HaloFour, 
ea-async currently supports instrumenting methods that return/await classes that derive from CompletionStage<T>. 

The only requirement is that those CompletionStages implement the method [CompletionStage.toCompletabeFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html#toCompletableFuture--)


```java
    public static <T, F extends CompletionStage<T>> T await(F future)
```

see one example here: https://github.com/electronicarts/ea-async/blob/master/async/src/test/java/com/ea/async/test/CompletionStageTest.java

Lettuce Redis RedisFuture seems to implement com.google.common.util.concurrent.ListenableFuture not CompletionStage.

Check its code: https://github.com/mp911de/lettuce/blob/master/src/main/java/com/lambdaworks/redis/RedisFuture.java

**Comment by DanielSperry** [comment]
I think there might be a case for supporting for google's and spring's ListenableFutures.

**Comment by HaloFour** [comment]
@DanielSperry 

They changed that in Lettuce 4.x:

https://github.com/mp911de/lettuce/blob/4.0/src/main/java/com/lambdaworks/redis/RedisFuture.java

I tried to implement this in a sample project and ea-async wouldn't instrument the class:

```java
package com.halofour;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.Future;

import static com.ea.async.Async.await;

public class Main {
    public interface MyFuture<T> extends CompletionStage<T>, Future<T> {
        static <T> MyFuture<T> completed(T result) {
            MyFutureImpl<T> future = new MyFutureImpl<>();
            future.complete(result);
            return future;
        }
    }

    private static class MyFutureImpl<T> extends CompletableFuture<T> implements MyFuture<T> { }

    public static void main(String[] args) throws Throwable {
        CompletionStage<String> future = getAsync();
        String result = future.toCompletableFuture().get();
        System.out.println(result);
    }

    public static MyFuture<String> getAsync() {
        String result = await(otherAsync());
        return MyFuture.completed(result);
    }

    public static MyFuture<String> otherAsync() {
        return MyFuture.completed("HELLO");
    }
}
```

Worse, if I change the return type of `getAsync` to `CompletionStage<String>` then the method is instrumented but execution produces a `VerifyError`:

```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/halofour/Main.getAsync()Ljava/util/concurrent/CompletionStage; @20: invokevirtual
  Reason:
    Type 'com/halofour/Main$MyFuture' (current frame, stack[0]) is not assignable to 'java/util/concurrent/CompletableFuture'
  Current Frame:
    bci: @20
    flags: { }
    locals: { top, 'com/halofour/Main$MyFuture' }
    stack: { 'com/halofour/Main$MyFuture', 'java/util/function/Function' }
  Bytecode:
    0x0000000: b800 4659 b900 2101 00b6 004a 9a00 184c
    0x0000010: 2bb8 0050 b600 542b 1100 01ba 0068 0000
    0x0000020: b600 6bb0 b900 2101 00b6 006e c000 294b
    0x0000030: 2ab8 0044 b0                           
  Stackmap Table:
    full_frame(@36,{},{Object[#12]})

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3035)
	at java.lang.Class.getMethod0(Class.java:3005)
	at java.lang.Class.getMethod(Class.java:1771)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```

**Comment by HaloFour** [comment]
@DanielSperry 

> I think there might be a case for supporting for google's and spring's ListenableFutures.

That would be awesome.  Would multiple shaded versions of ASM need to be used in order to produce bytecode compatible with different versions of the JVM, or would you only target 8.0+?

Even better might be something that would allow pluggable instrumentation, although I have no idea how that would work.  The project I'm working on is a Jersey REST server and we use our own Promise-like class due to legacy reasons.  Internally it uses `CompletableFuture<T>` now but the public methods aren't compatible.  I'm pushing for adoption of ea-async since frankly callback-style asynchrony bakes a lot of noodles.

**Comment by DanielSperry** [comment]
So:

1) not instrumenting something that returns anything other than CompletionStage or CompletabeFuture makes sense. I botched my first response. I should have said your method must return CompletionStage or CompletableFuture. It can't just return any future because what the instrumentation does is to replace:

await(fut);

with:

if(!fut.[toCompletableFuture()].isDone()) {
   return fut.exceptionally(nop).thenCompose((...) -> async$yourmethod).[toCompletableFuture()];
} else {
   fut.join();
}

It means that the response of fut.exceptionally.thenCompose  must be of the same type of the return of your method. 

----

2) All that being said. The verification error is certainly a bug with the ea-async instrumentation. 
(probably with the stack dataflow analysis)

**Comment by HaloFour** [comment]
@DanielSperry 

Makes sense.  Shouldn't the incompatible return type have tripped the warning on a non-async method during instrumentation and caused the maven build to fail?

**Comment by DanielSperry** [comment]
Yes, it should. But since apparently the generated bytecode is wrong and the class is not being loaded during the build time instrumentation (I'm assuming you are doing build time instrumentation with the ea-async-plugin) then the bytecode is only being verified by the jvm when you run it.

We need to and fix this particular bug. And look into letting the jvm validate the instrumented classes during build time instrumentation (might be trickier than it sounds).

**Comment by HaloFour** [comment]
@DanielSperry

I meant specifically warning that the method that was calling `Async#await` wasn't returning either `CompletionStage<T>` or `CompletableFuture<T>` and thus would not be instrumented.  However if instrumentation could validate that the generated bytecode is verifiable that would probably be a good thing, catch issues before they explode at runtime.

**Comment by DanielSperry** [comment]
Quite a backlog here... 

  - Check why the uninstrumentable methods are not being reported (they should have been)
  - Fix that verification error.
  - Investigate the feasibility of supporting some other futures (google's and spring's)

**Comment by JoeHegarty** [comment]
This issue has been idle for a very long time. I'm going to close this for now.
Please feel free to open other issues to follow up on any of these points.
