### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by lukyer** [electronicarts/ea-async#35]
Any plans for LTS Java 11? :)

**Comment by JoeHegarty** [comment]
I believe this should already work with any of the JDK 11s based on OpenJDK. 
I haven't tested but I believe it should work with Corretto, Azul Zulu and Oracle.

Did you have something specific in mind that isn't currently working?

**Comment by Ranger-118** [comment]
Tested fine with JDK 11, I thought it ends up with JDK 10 too at the beginning as it's been mentioned in README that JDK 8-10 are supported. It would be better to update it to the latest support version. Thanks for this project anyway!
