### ISSUE TITLE
Sounds like a good idea...

### ISSUE THREAD

**Issue by neilyoung** [electronicarts/ea-async#64]
...does not work.

Crashes immediately in Async.init()

```
2023-06-06 16:57:53.160  3727-3727  AndroidRuntime          com.example.myapp                E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.myapp, PID: 3727
                                                                                                    java.lang.ExceptionInInitializerError

```

**Comment by HaloFour** [comment]
I think you need to use compile-time instrumentation in order to get it to work on Android as Davlik lacks the agent instrumentation capabilities of the full JVM?

**Comment by neilyoung** [comment]
Whatever this means..

**Comment by neilyoung** [comment]
Anyway, don't bother with this. I put it aside.

**Comment by HaloFour** [comment]
It means that `Async.init()` can't work because Android doesn't use a proper Java runtime.  There are maven and gradle build plugins provided which can perform the transformations at compile-time so that it doesn't depend on a specific runtime, and should be able to run on Android.

**Comment by neilyoung** [comment]
Well, I'm using the gradle plugin, but maybe wrong.

    implementation 'com.ea.async:ea-async:1.2.3'

then 

 static {
        Async.init();
    }

There was no other condition mentioned
